AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    FtfWebManagementRecorder
    and FtfWebManagement DynamoDB setup

######################################################
# Parameters:
######################################################
Parameters:
    NameTag:
        Type: String
        Default: it1
        AllowedValues:
            - it1
            - it2
            - it3
            - it4
            - it5
            - stg1
            - stg2
            - prod
        Description: Enter profile.
######################################################
# Resources
######################################################
Resources:
    #----------------------------------------------
    # FOOD:FOOD_*
    #----------------------------------------------
    FOOD:
        Type: AWS::DynamoDB::Table
        Properties:
            KeySchema:
                - AttributeName: shop_name_food_type
                  KeyType: HASH
                - AttributeName: id
                  KeyType: RANGE
            AttributeDefinitions:
                - AttributeName: shop_name_food_type
                  AttributeType: S
                - AttributeName: id
                  AttributeType: N
                - AttributeName: wholesaler_id
                  AttributeType: N
                - AttributeName: material_code
                  AttributeType: S
                - AttributeName: material_type
                  AttributeType: S
            GlobalSecondaryIndexes:
                - IndexName: shop_name_food_type-wholesaler_id-index
                  KeySchema:
                      - AttributeName: shop_name_food_type
                        KeyType: HASH
                      - AttributeName: wholesaler_id
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
                - IndexName: shop_name_food_type-material_code-index
                  KeySchema:
                      - AttributeName: shop_name_food_type
                        KeyType: HASH
                      - AttributeName: material_code
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
                - IndexName: shop_name_food_type-material_type-index
                  KeySchema:
                      - AttributeName: shop_name_food_type
                        KeyType: HASH
                      - AttributeName: material_type
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
            TableName:
                !Join [
                    "_",
                    ["FOOD", !Ref NameTag],
            ]
            BillingMode: PAY_PER_REQUEST
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            SSESpecification:
                SSEEnabled: true

    #----------------------------------------------
    # SEQUENCE:SEQUENCE*
    #----------------------------------------------
    SEQUENCE:
        Type: AWS::DynamoDB::Table
        Properties:
            KeySchema:
                - AttributeName: table_name
                  KeyType: HASH
                - AttributeName: partition_key
                  KeyType: RANGE
            AttributeDefinitions:
                - AttributeName: table_name
                  AttributeType: S
                - AttributeName: partition_key
                  AttributeType: S
            TableName:
                !Join [
                    "_",
                    ["SEQUENCE", !Ref NameTag],
            ]
            BillingMode: PAY_PER_REQUEST
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            SSESpecification:
                SSEEnabled: true
    
    #----------------------------------------------
    # STOCK:STOCK_*
    #----------------------------------------------
    STOCK:
        Type: AWS::DynamoDB::Table
        Properties:
            KeySchema:
                - AttributeName: shop_name_food_type
                  KeyType: HASH
                - AttributeName: id
                  KeyType: RANGE
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: N
                - AttributeName: shop_name_food_type
                  AttributeType: S
            TableName:
                !Join [
                    "_",
                    ["STOCK", !Ref NameTag],
            ]
            BillingMode: PAY_PER_REQUEST
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            SSESpecification:
                SSEEnabled: true

    #----------------------------------------------
    # FLOW:FLOW_*
    #----------------------------------------------
    FLOW:
        Type: AWS::DynamoDB::Table
        Properties:
            KeySchema:
                - AttributeName: shop_name_food_type
                  KeyType: HASH
                - AttributeName: date
                  KeyType: RANGE
            AttributeDefinitions:
                - AttributeName: shop_name_food_type
                  AttributeType: S
                - AttributeName: date
                  AttributeType: S
            TableName:
                !Join [
                    "_",
                    ["FLOW", !Ref NameTag],
            ]
            BillingMode: PAY_PER_REQUEST
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            SSESpecification:
                SSEEnabled: true

    #----------------------------------------------
    # WHOLESALER:WHOLESALER_*
    #----------------------------------------------
    WHOLESALER:
        Type: AWS::DynamoDB::Table
        Properties:
            KeySchema:
                - AttributeName: shop_name
                  KeyType: HASH
                - AttributeName: id
                  KeyType: RANGE
            AttributeDefinitions:
                - AttributeName: shop_name
                  AttributeType: S
                - AttributeName: id
                  AttributeType: N
            TableName:
                !Join [
                    "_",
                    ["WHOLESALER", !Ref NameTag],
            ]
            BillingMode: PAY_PER_REQUEST
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            SSESpecification:
                SSEEnabled: true

    #----------------------------------------------
    # HOLIDAY:HOLIDAY*
    #----------------------------------------------
    HOLIDAY:
        Type: AWS::DynamoDB::Table
        Properties:
            KeySchema:
                - AttributeName: date
                  KeyType: HASH
            AttributeDefinitions:
                - AttributeName: date
                  AttributeType: S
            TableName:
                !Join [
                    "_",
                    ["HOLIDAY", !Ref NameTag],
            ]
            BillingMode: PAY_PER_REQUEST
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            SSESpecification:
                SSEEnabled: true

    #----------------------------------------------
    # SHOP:SHOP*
    #----------------------------------------------
    SHOP:
        Type: AWS::DynamoDB::Table
        Properties:
            KeySchema:
                - AttributeName: shop_name
                  KeyType: HASH
            AttributeDefinitions:
                - AttributeName: shop_name
                  AttributeType: S
            TableName:
                !Join [
                    "_",
                    ["SHOP", !Ref NameTag],
            ]
            BillingMode: PAY_PER_REQUEST
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            SSESpecification:
                SSEEnabled: true

    #----------------------------------------------
    # BUSINESS_DATE:BUSINESS_DATE_*
    #----------------------------------------------
    BUSINESSDATE:
        Type: AWS::DynamoDB::Table
        Properties:
            KeySchema:
                - AttributeName: shop_name
                  KeyType: HASH
                - AttributeName: date
                  KeyType: RANGE
            AttributeDefinitions:
                - AttributeName: shop_name
                  AttributeType: S
                - AttributeName: date
                  AttributeType: S
                - AttributeName: day
                  AttributeType: N
            GlobalSecondaryIndexes:
                - IndexName: shop_name-day-index
                  KeySchema:
                      - AttributeName: shop_name
                        KeyType: HASH
                      - AttributeName: day
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
            TableName:
                !Join [
                    "_",
                    ["BUSINESS_DATE", !Ref NameTag],
            ]
            BillingMode: PAY_PER_REQUEST
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            SSESpecification:
                SSEEnabled: true

    #----------------------------------------------
    # ORDER:ORDER_*
    #----------------------------------------------
    ORDER:
        Type: AWS::DynamoDB::Table
        Properties:
            KeySchema:
                - AttributeName: shop_name
                  KeyType: HASH
                - AttributeName: date
                  KeyType: RANGE
            AttributeDefinitions:
                - AttributeName: shop_name
                  AttributeType: S
                - AttributeName: date
                  AttributeType: S
            TableName:
                !Join [
                    "_",
                    ["ORDER", !Ref NameTag],
            ]
            BillingMode: PAY_PER_REQUEST
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            SSESpecification:
                SSEEnabled: true