AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    FtfWebManagementRecorder
    and FtfWebManagement DynamoDB setup

######################################################
# Parameters:
######################################################
Parameters:
    NameTag:
        Type: String
        Default: it1
        AllowedValues:
            - it1
            - it2
            - it3
            - it4
            - it5
            - stg1
            - stg2
            - prod
        Description: Enter profile.
######################################################
# Resources
######################################################
Resources:
    #----------------------------------------------
    # MATERIAL:MATERIAL_*
    #----------------------------------------------
    MATERIAL:
        Type: AWS::DynamoDB::Table
        Properties:
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: N
                - AttributeName: wholesaler_id
                  AttributeType: N
                - AttributeName: material_code
                  AttributeType: S
                - AttributeName: material_type
                  AttributeType: S
            GlobalSecondaryIndexes:
                - IndexName: wholesaler_id-id-index
                  KeySchema:
                      - AttributeName: wholesaler_id
                        KeyType: HASH
                      - AttributeName: id
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
                - IndexName: material_code-index
                  KeySchema:
                      - AttributeName: material_code
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
                - IndexName: material_type-index
                  KeySchema:
                      - AttributeName: material_type
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
            TableName:
                !Join [
                    "_",
                    ["MATERIAL", !Ref NameTag],
            ]
            BillingMode: PAY_PER_REQUEST
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            SSESpecification:
                SSEEnabled: true

    #----------------------------------------------
    # PRODUCT:PRODUCT_*
    #----------------------------------------------
    PRODUCT:
        Type: AWS::DynamoDB::Table
        Properties:
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: N
                - AttributeName: menu_type
                  AttributeType: S
                - AttributeName: product_type_1
                  AttributeType: S
                - AttributeName: product_type_2
                  AttributeType: S
                - AttributeName: product_type_3
                  AttributeType: S
            GlobalSecondaryIndexes:
                - IndexName: menu_type-id-index
                  KeySchema:
                      - AttributeName: menu_type
                        KeyType: HASH
                      - AttributeName: id
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
                - IndexName: product_type_1-id-index
                  KeySchema:
                      - AttributeName: product_type_1
                        KeyType: HASH
                      - AttributeName: id
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
                - IndexName: product_type_2-id-index
                  KeySchema:
                      - AttributeName: product_type_2
                        KeyType: HASH
                      - AttributeName: id
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
                - IndexName: product_type_3-id-index
                  KeySchema:
                      - AttributeName: product_type_3
                        KeyType: HASH
                      - AttributeName: id
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
            TableName:
                !Join [
                    "_",
                    ["PRODUCT", !Ref NameTag],
            ]
            BillingMode: PAY_PER_REQUEST
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            SSESpecification:
                SSEEnabled: true

    #----------------------------------------------
    # INGREDIENT:INGREDIENT_*
    #----------------------------------------------
    INGREDIENT:
        Type: AWS::DynamoDB::Table
        Properties:
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: N
            TableName:
                !Join [
                    "_",
                    ["INGREDIENT", !Ref NameTag],
            ]
            BillingMode: PAY_PER_REQUEST
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            SSESpecification:
                SSEEnabled: true

    #----------------------------------------------
    # BASE_ITEM:BASE_ITEM_*
    #----------------------------------------------
    BASEITEM:
        Type: AWS::DynamoDB::Table
        Properties:
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: N
            TableName:
                !Join [
                    "_",
                    ["BASE_ITEM", !Ref NameTag],
            ]
            BillingMode: PAY_PER_REQUEST
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            SSESpecification:
                SSEEnabled: true
    
    #----------------------------------------------
    # SEQUENCE:SEQUENCE*
    #----------------------------------------------
    SEQUENCE:
        Type: AWS::DynamoDB::Table
        Properties:
            KeySchema:
                - AttributeName: table_name
                  KeyType: HASH
            AttributeDefinitions:
                - AttributeName: table_name
                  AttributeType: S
            TableName:
                !Join [
                    "_",
                    ["SEQUENCE", !Ref NameTag],
            ]
            BillingMode: PAY_PER_REQUEST
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            SSESpecification:
                SSEEnabled: true
    
    #----------------------------------------------
    # STOCK:STOCK_*
    #----------------------------------------------
    STOCK:
        Type: AWS::DynamoDB::Table
        Properties:
            KeySchema:
                - AttributeName: food_type
                  KeyType: HASH
                - AttributeName: id
                  KeyType: RANGE
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: N
                - AttributeName: food_type
                  AttributeType: S
            TableName:
                !Join [
                    "_",
                    ["STOCK", !Ref NameTag],
            ]
            BillingMode: PAY_PER_REQUEST
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            SSESpecification:
                SSEEnabled: true

    #----------------------------------------------
    # FLOW:FLOW_*
    #----------------------------------------------
    FLOW:
        Type: AWS::DynamoDB::Table
        Properties:
            KeySchema:
                - AttributeName: food_type
                  KeyType: HASH
                - AttributeName: date
                  KeyType: RANGE
            AttributeDefinitions:
                - AttributeName: food_type
                  AttributeType: S
                - AttributeName: date
                  AttributeType: S
            TableName:
                !Join [
                    "_",
                    ["FLOW", !Ref NameTag],
            ]
            BillingMode: PAY_PER_REQUEST
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            SSESpecification:
                SSEEnabled: true